Add bootstrap5
IF-122-Ruby/giftify pull request #10
Opened 2021-05-26 21:31 UTC by SashaDi13

Config bootstrap5

2021-05-27 06:21 UTC, manastyretskyi commented on app/helpers/static_pages_helper.rb
> +end
пусті файли видаляйте

2021-05-27 06:22 UTC, manastyretskyi commented on app/javascript/stylesheets/static_pages.scss
> +}
щось я сумніваюся що це хороша ідея задавати марджин для всіх кнопок на сайті

2021-05-27 06:23 UTC, manastyretskyi commented on babel.config.js
> -        }
для чого ці всі зміни?

2021-05-27 06:23 UTC, manastyretskyi commented on config/routes.rb
> +  get 'static_pages/about'
задай якісь нормальні роути

2021-05-27 06:23 UTC, manastyretskyi commented on config/webpacker.yml
> -    - .jsx
для чого це забирати?

2021-05-27 06:26 UTC, manastyretskyi commented on package-lock.json
> +  "lockfileVersion": 1,
видали цей файл, на проектах всі юзають `yarn` замість `npm`

2021-05-27 06:29 UTC, manastyretskyi commented on app/views/static_pages/about.html.slim
> +p Find me in app/views/static_pages/about.html.slim
якщо уже додав цю в'юшку, то заповни її якимось нормальним контентом

2021-05-27 06:30 UTC, manastyretskyi commented on app/views/static_pages/contact_us.html.slim
> +p Find me in app/views/static_pages/contact_us.html.slim
тут те саме що й в коменті [вище](https://github.com/IF-122-Ruby/giftify/pull/10/files#r640323006)

2021-05-27 06:30 UTC, manastyretskyi commented
там був темплейт для пулріквеста який я просив заповнювати, але ти чомусь всьо видалив

2021-05-27 06:31 UTC, manastyretskyi commented
додай якісь скріншоти до дескріпшена ПРа

2021-05-27 15:54 UTC, SashaDi13 commented
Fixing configuration bootstrap, add root to routes

2021-05-27 16:54 UTC, everlastroman approved these changes

2021-05-27 16:55 UTC, dimk0o approved these changes
approved

2021-05-27 17:19 UTC, manastyretskyi commented on app/views/layouts/application.html.erb
> +</div>
це що таке?

2021-05-27 17:22 UTC, manastyretskyi commented on package.json
> +    "popper.js": "^1.16.1",
він у тебе підключений і через гем, і через вебпакер, треба вибрати щось одне

2021-05-27 17:31 UTC, VasylenchukMischa commented on app/views/layouts/application.html.erb
> +</div>
Це для тесту бутстрапа і має бути видалене

2021-05-27 18:26 UTC, VasylenchukMischa approved these changes

2021-05-27 18:42 UTC, everlastroman approved these changes

2021-05-27 19:00 UTC, igorkasyanchuk commented on app/javascript/stylesheets/static_pages.scss
> +header {
Стилі хедера винеси в header. Scss зроби окремий файл
Стилі по body - styles.scss

І тд

2021-05-27 19:01 UTC, igorkasyanchuk commented on app/views/static_pages/home.html.slim
> +  header
Розбий на паршали і в лайауті підключи

2021-05-27 19:01 UTC, igorkasyanchuk commented on spec/helpers/static_pages_helper_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Видали цей тест

2021-05-27 19:01 UTC, igorkasyanchuk commented on spec/views/static_pages/home.html.slim_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Видали цей тест на вьюхи і іншим скажи

2021-05-27 19:02 UTC, igorkasyanchuk commented on spec/requests/static_pages_spec.rb
> +  describe "GET /home" do
Додай в тест контролера render_views
Розкажеш усім що воно робить

2021-05-28 06:26 UTC, manastyretskyi commented on package.json
> +    "popper.js": "^1.16.1",
якщо уже видалив бутстрап звідси, то повидаляй і ліби які він юзає

2021-05-28 06:27 UTC, manastyretskyi commented on config/routes.rb
> +  root 'static_pages#home'
```suggestion
  root to: 'static_pages#home'
```

2021-05-28 06:28 UTC, manastyretskyi commented on app/javascript/packs/application.js
> +import "../stylesheets/application"
a воно у тебе взагалі працює? ти ніби видалив бутстрап з package.json

2021-05-28 06:59 UTC, SashaDi13 commented on app/javascript/packs/application.js
> +import "../stylesheets/application"
Працює, ви казали видали бутстрап або з гем файлу або з вебпакера, якщо видалити з гем файлу, то бутстрап не працює, а якщо з вебпакеру, то працює, тому видалила з вебпакеру

2021-05-28 08:03 UTC, manastyretskyi commented on app/javascript/packs/application.js
> +import "../stylesheets/application"
ти досліджувала чому він не працює через вебпакер?

2021-05-28 12:35 UTC, manastyretskyi commented on spec/requests/static_pages_spec.rb
> +      get "/static_pages/home"
```suggestion
      get "/"
```

2021-05-28 21:32 UTC, DenysVinegod approved these changes

2021-05-29 07:52 UTC, VasylenchukMischa commented on app/javascript/packs/application.js
> +require("jquery")
А чому ти використала require? З import якісь проблеми?

2021-05-29 07:53 UTC, VasylenchukMischa commented on app/javascript/stylesheets/application.scss
> +@import "style";
Це надто узагальнена назва

2021-05-29 07:55 UTC, VasylenchukMischa commented on package.json
> +    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
Видали це

2021-05-29 07:56 UTC, VasylenchukMischa commented on babel.config.js
> +        }
Це теж треба видалити

2021-05-29 08:05 UTC, SashaDi13 commented on app/javascript/packs/application.js
> +require("jquery")
так, через імпорт не всі стилі підключаються

2021-05-29 08:05 UTC, SashaDi13 commented on app/javascript/stylesheets/application.scss
> +@import "style";
я мала це видалити

2021-05-29 08:10 UTC, VasylenchukMischa commented on app/javascript/packs/application.js
> +require("jquery")
А навіщо тоді підключати всі модулі через require? Та і імпорт мав би все підключити

2021-05-30 19:31 UTC, manastyretskyi commented on app/assets/stylesheets/application.css
>   */
цей файл переіменуй в `application.scss`, і використовуй імпорти `scss`

2021-05-30 19:32 UTC, manastyretskyi commented on app/assets/stylesheets/header.scss
> +  }
між класами бажано додавати нову строку, читабельніше стає

2021-05-30 19:33 UTC, manastyretskyi commented on app/helpers/application_helper.rb
> -module ApplicationHelper
цей хелпер бажано все ж лишити, він в новому проекті не просто так є, а інші хелпери треба видаляти якщо вони пусті

2021-05-30 19:34 UTC, manastyretskyi commented on app/javascript/packs/application.js
> +import "assets/application"
щось я не розумію для чого це, і чому воно взагалі працює

2021-05-30 19:38 UTC, manastyretskyi commented on app/views/layouts/application.slim
> +doctype html
те як ти цей файл назвала це не добре, треба вказувати формат, щоб рельси знали в якому саме випадку рендерити цей леяут, наприклад `application.html.slim` буде рендеритися коли формат ріквеста `html`, а так як він зараз названий, то його рельси можуть відрендерити навіть якщо формат ріквеста буде `json`

2021-05-30 19:39 UTC, manastyretskyi commented on app/views/layouts/application.slim
> +doctype html
Той самий комент до всіх інших паршиалів і в'ю в яких формат не вказаний

2021-05-30 19:40 UTC, manastyretskyi commented on config/webpack/environment.js
> +    }))
Ігор здається казав вам що jquery не треба підключати

2021-05-31 05:39 UTC, igorkasyanchuk commented on config/webpack/environment.js
> +    }))
Так, без jquery

2021-05-31 07:29 UTC, manastyretskyi requested changes
Додай якісь скріншоти того що є

2021-05-31 07:29 UTC, manastyretskyi commented on Gemfile
> +#gem 'bootstrap', '~> 5.0.0.beta1'
якщо цього не треба, то видали

2021-05-31 07:29 UTC, manastyretskyi commented on app/assets/stylesheets/application.scss
> + *= require bootstrap
ці всі коменти можеш видалити

2021-05-31 07:29 UTC, manastyretskyi commented on app/javascript/packs/application.js
> +// import "assets/application"
якщо цього не треба, видаляй

2021-05-31 07:29 UTC, manastyretskyi commented on app/views/layouts/application.html.slim
> +      = render "header"
може цей `header` в паршиал перемістити?

2021-05-31 07:29 UTC, manastyretskyi commented on babel.config.js
> +        }
За ці зміни уже писав, але мене проігнорували, напишу ще раз, для чого вони?

2021-05-31 07:29 UTC, manastyretskyi commented on config/webpack/environment.js
> +// const webpack = require('webpack')
Не потрібні коменти видаляй

2021-05-31 07:29 UTC, manastyretskyi commented on package.json
> +    "popper.js": "^1.16.1",
Якщо уже вирішила підключати бутстрап через гем, то позабирай звідси ці ліби

2021-05-31 07:29 UTC, manastyretskyi commented on spec/helpers/static_pages_helper_spec.rb
> +# end
Цього хелпера немає, можеш видалити спек для нього

2021-05-31 07:29 UTC, manastyretskyi commented on spec/requests/static_pages_spec.rb
> +end
може зробити тест що ріспонс має статут 200?

2021-05-31 07:29 UTC, manastyretskyi commented on config/routes.rb
>    devise_for :users, controllers: {
додай нову строку між ними, читабельніше буде

2021-05-31 07:35 UTC, SashaDi13 commented on babel.config.js
> +        }
їх немає бути, я зараз заберу

2021-05-31 07:38 UTC, manastyretskyi commented on package.json
> +    "popper.js": "^1.16.1",
Особисто я б казав ставити п'ятий бутстрап не через гем, а через вебпакер

2021-05-31 07:40 UTC, manastyretskyi commented on package.json
> +    "popper.js": "^1.16.1",
може ця [стаття](https://dev.to/yarotheslav/install-bootstrap-5-with-ruby-on-rails-6-replace-bootstrap-4-2bf9) допоможе (те що вона 100% робоча я не перевіряв, але мені виглядає що все ок по його туторіалу має бути)

2021-05-31 07:44 UTC, SashaDi13 commented on package.json
> +    "popper.js": "^1.16.1",
дякую, зараз подивлюсь

2021-05-31 07:46 UTC, SashaDi13 commented on package.json
> +    "popper.js": "^1.16.1",
я робила так

2021-05-31 08:09 UTC, manastyretskyi commented on package.json
> +    "popper.js": "^1.16.1",
там напевно не працювали стилі, так?

2021-05-31 09:58 UTC, manastyretskyi commented on Gemfile
> +#gem 'bootsnap', '>= 1.4.4', require: false
це не ок, тут має бути якийсь інший солюшен

2021-05-31 14:56 UTC, manastyretskyi commented on app/assets/stylesheets/application.css
> + *= require bootstrap
цього не треба уже

2021-05-31 14:56 UTC, manastyretskyi commented on app/javascript/stylesheets/header.scss
> +  }
```suggestion
  height: 100rem;

  .text_color {
    color: #fff;
  }
```

2021-05-31 14:56 UTC, manastyretskyi commented on app/javascript/stylesheets/header.scss
> +  }
```suggestion
  border-color: $main-color;

  &:hover {
    background-color: $main-color-hover;
  }
```

2021-05-31 14:57 UTC, manastyretskyi commented on app/views/layouts/application.html.slim
> +    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
`stylesheet_link_tag` треба було лишити

2021-05-31 14:59 UTC, SashaDi13 commented on app/views/layouts/application.html.slim
> +    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
тобто і stylesheet_pack_tag і stylesheet_link_tag?

2021-05-31 15:09 UTC, manastyretskyi commented on app/views/layouts/application.html.slim
> +    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
так

2021-05-31 15:09 UTC, manastyretskyi commented on app/views/layouts/application.html.slim
> +    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
одне іншому не мішає)

2021-05-31 15:10 UTC, SashaDi13 commented on app/views/layouts/application.html.slim
> +    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
ок

2021-05-31 15:18 UTC, SashaDi13 commented
![Screenshot from 2021-05-31 18-13-02](https://user-images.githubusercontent.com/61061910/120214038-96471800-c23c-11eb-9776-723ff8491d56.png)

Виглядає поки не оч

2021-06-01 07:00 UTC, merged