Add admin layout
IF-122-Ruby/giftify pull request #11
Opened 2021-05-27 10:06 UTC by MantaPrograming

# [Issue title](https://issueurl)
Create layout and partials for admin panel
## Changes description

## Screnshots of the added pages

## Check list:
- [ ] Integration Tests
- [ ] Functional
- [ ] Unit
- [ ] Factories
- [ ] Updated seed file

2021-05-28 12:37 UTC, manastyretskyi commented on app/views/layouts/admin.html.slim
> +    = render :partial => './shared/navbar'
```suggestion
    = render partial: './shared/navbar'
```

2021-05-28 12:40 UTC, manastyretskyi commented on app/views/layouts/admin.html.slim
> += render :partial => './shared/footer'
```suggestion
= render partial: 'shared/footer'
```

2021-06-02 09:07 UTC, matsevich reviewed
please add some screenshots of your layout

2021-06-02 11:19 UTC, MantaPrograming commented
> please add some screenshots of your layout

add

2021-06-02 11:32 UTC, igorkasyanchuk commented on app/controllers/admin_controller.rb
> +  @user = User.all
Якщо множина то чому змінна називається в однині

2021-06-02 11:32 UTC, igorkasyanchuk commented on app/helpers/static_pages_helper.rb
> +module StaticPagesHelper
Видаляй пустий файл

2021-06-02 11:33 UTC, igorkasyanchuk commented on app/views/admin/admin.html.slim
> +    script[src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"]
Забери jquery

2021-06-02 11:33 UTC, igorkasyanchuk commented on app/views/admin/shared/_content.html.slim
> +    h2 Maneging organizations
Англ не гуд

2021-06-02 11:34 UTC, igorkasyanchuk commented on app/views/admin/shared/_content.html.slim
> +                  = organization.created_at
Виведи дату через l..., format short

2021-06-02 11:36 UTC, igorkasyanchuk commented on app/views/admin/shared/_developers.html.slim
> +          .col-lg-2.col-md-4.col-sm-6.pb-4
Код повторюється про дева. Винеси в паршал і передавай дані

2021-06-02 11:36 UTC, igorkasyanchuk commented on app/views/admin/shared/_navbar.html.slim
> +          #Registration.modal.fade[tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"]
Нащо ця модалка якщо вона не працює?

2021-06-02 11:37 UTC, MantaPrograming commented on app/controllers/admin_controller.rb
> +  @user = User.all
Зара зміню, дякую

2021-06-02 11:37 UTC, igorkasyanchuk commented on app/views/admin/shared/_statistic.html
> +<div class="container">
А це що за html вьюха

2021-06-02 11:38 UTC, igorkasyanchuk commented on app/views/admin/shared/_statistic.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
Забирай цей js

2021-06-02 11:38 UTC, igorkasyanchuk commented on app/views/admin/shared/_statistic.html
> +      fillColor: "#fff",
Забирай статистику взагалі. Буде робитись окремим таском

2021-06-02 11:39 UTC, igorkasyanchuk commented on app/views/admin/shared/_users_all.html.slim
> +      - @user.each do |user|
@users

2021-06-02 11:39 UTC, igorkasyanchuk commented on package-lock.json
> +{
А що за файл вище newfile.txt

2021-06-02 11:50 UTC, MantaPrograming commented on app/views/admin/shared/_navbar.html.slim
> +          #Registration.modal.fade[tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"]
Планував що в цих модалках будуть рендеритись форми реєстрації, які зроблять в наступних гілках

2021-06-02 11:51 UTC, MantaPrograming commented on app/views/admin/shared/_statistic.html
> +<div class="container">
паршал, статистики не працював у слім варіанті

2021-06-02 12:17 UTC, manastyretskyi commented on app/views/admin/shared/_statistic.html
> +<div class="container">
з мого досвіду в слімі працює все, якщо код робочий само собою ; )

2021-06-02 12:18 UTC, manastyretskyi commented on package.json
>      "@rails/actioncable": "^6.0.0",
раз почав, то уже й `actioncable` треба було обновити

2021-06-02 12:19 UTC, manastyretskyi commented on package-lock.json
> +{
цей файл видали, і користуйся ярном

2021-06-02 12:19 UTC, manastyretskyi commented on app/views/layouts/application.html.slim
> +    = render "./static_pages/header"
що це за крапочка на початку, для чого вона?

2021-06-02 12:20 UTC, manastyretskyi commented on app/views/admin/shared/_navbar.html.slim
> +    nav.navbar.navbar-expand-lg.navbar-light[style="background-color: #734dbb;  "]
чому тут в файлі зразу відступ в два таба?

2021-06-02 12:21 UTC, manastyretskyi commented on app/views/admin/admin.html.slim
> +          = render partial: 'admin/shared/content'
десь пишеш `render partial: ...`, а десь просто `render ...`, якось одинаково роби

2021-06-02 12:22 UTC, manastyretskyi commented on app/views/admin/_footer.html.slim
> +      section[style="color: white;"]
щось спейсінг тут не гуд, чому тут 6 табів?

2021-06-02 12:22 UTC, manastyretskyi commented on app/javascript/packs/application.js
> -ActiveStorage.start()
навіщо це забирати?

2021-06-02 12:22 UTC, manastyretskyi commented on app/controllers/static_pages_controller.rb
> +
для чого це?

2021-06-02 12:23 UTC, manastyretskyi commented on app/controllers/admin_controller.rb
> +
для чого тут ці пробіли?

2021-06-02 13:00 UTC, matsevich commented on app/views/admin/_footer.html.slim
> +      section[style="color: white;"]
@manastyretskyi  ви їм дозволяєте інлайн стилі юзати?

2021-06-02 13:07 UTC, manastyretskyi commented on app/views/admin/_footer.html.slim
> +      section[style="color: white;"]
писав інші коменти, інлайн стилі і не замітив) Взагалі не треба таке писати, це така собі практика

2021-06-02 13:12 UTC, MantaPrograming commented on app/views/layouts/application.html.slim
> +    = render "./static_pages/header"
це не з мого таска.

2021-06-02 13:13 UTC, MantaPrograming commented on app/views/admin/shared/_navbar.html.slim
> +    nav.navbar.navbar-expand-lg.navbar-light[style="background-color: #734dbb;  "]
виправив

2021-06-02 13:19 UTC, MantaPrograming commented on app/controllers/static_pages_controller.rb
> +
не з моєї таски

2021-06-02 15:24 UTC, MantaPrograming commented on app/views/admin/_footer.html.slim
> +      section[style="color: white;"]
переписав стилі у файл

2021-06-02 18:15 UTC, manastyretskyi commented on app/controllers/static_pages_controller.rb
> +
я про пусту строку

2021-06-02 18:16 UTC, manastyretskyi commented on app/javascript/stylesheets/admin.scss
> +.tc{
робіть відступи між класами, набагато читабельніше буде

2021-06-03 10:30 UTC, manastyretskyi commented on app/controllers/admin_controller.rb
> +                   {name: "Serhii",last_name: "Posternak", avatar: "https://i.ibb.co/QP1xyGT/1.png"}]
щось мені це не дуже подобається, якщо уже захардкоджено значення, то чому просто в ассети аватраки не засунути, для чого посилання на зовнішній ресурс? і ще, зроби це як локальну змінну у в'юшці

2021-06-03 10:32 UTC, manastyretskyi commented on config/routes.rb
> +  get '/admin', to: 'admin#admin'
`admin#admin` це не ок, давай екшин якось краще назви

2021-06-03 10:33 UTC, manastyretskyi commented on config/routes.rb
> +  get '/admin', to: 'admin#admin'
Взагалі, я б цей роут зробив як `root to: '...' `в середині неймспейса адміна, і тоді буде хелпер `admin_root_path`

2021-06-03 10:34 UTC, manastyretskyi commented on app/views/static_pages/_header.html.slim
> +    img.logo src="https://i.ibb.co/McTWtRr/giftify.png"
чому тут посилання на якийсь сторонній ресурс, чому просто в ассети це не засунути?

2021-06-03 10:35 UTC, manastyretskyi commented on app/views/admin/admin.html.slim
> +    script[src="https://www.google.com/jsapi"]
що це таке?

2021-06-03 10:37 UTC, manastyretskyi commented on app/views/admin/admin.html.slim
> +doctype html
Зроби окремий леяут для цього неймспейса, і в базовому контролері пропиши щоб він юзався

2021-06-03 10:45 UTC, MantaPrograming commented on app/views/static_pages/_header.html.slim
> +    img.logo src="https://i.ibb.co/McTWtRr/giftify.png"
Ми начебто на хероку малиб проект розгортати, хероку свариться на картинки каже щоб були лінки, можу переробити не проблема

2021-06-03 11:45 UTC, manastyretskyi commented on app/views/static_pages/_header.html.slim
> +    img.logo src="https://i.ibb.co/McTWtRr/giftify.png"
Вперше чую таке що на хероку не можна асети додавати

2021-06-03 13:55 UTC, MantaPrograming commented on config/routes.rb
> +  get '/admin', to: 'admin#admin'
це вже діана зробила в своїй гілці

2021-06-03 15:05 UTC, MantaPrograming commented on app/views/static_pages/_header.html.slim
> +    img.logo src="https://i.ibb.co/McTWtRr/giftify.png"
в мене на 4 рельсах таке було, в хлопців попитав кажуть що на 6 все норм

2021-06-03 16:13 UTC, manastyretskyi commented on app/helpers/public_pages_helper.rb
> +               {name: "Serhii",last_name: "Posternak", avatar: "serhii.png"}]
просто в в'ю це задефайнь, не треба цієї константи і хелпера

2021-06-03 16:16 UTC, manastyretskyi requested changes

2021-06-03 16:16 UTC, manastyretskyi commented on app/views/admin/index.html.slim
> +doctype html
Уже писав, напишу ще раз, зроби окремий леяут для адмінки

2021-06-03 16:16 UTC, manastyretskyi commented on app/views/admin/shared/_content.html.slim
> +    p
для чого це?

2021-06-03 16:16 UTC, manastyretskyi commented on app/views/admin/shared/_sidebar.html.slim
> +    .col-1.color-bg.bgc.wrap
лишні таби

2021-06-03 16:28 UTC, MantaPrograming commented on app/views/admin/shared/_content.html.slim
> +    p
прибрав

2021-06-03 16:28 UTC, MantaPrograming commented on app/views/admin/shared/_sidebar.html.slim
> +    .col-1.color-bg.bgc.wrap
прибрав

2021-06-03 20:22 UTC, manastyretskyi commented on app/controllers/admin_controller.rb
> +  def index
```suggestion
  layout "admin"

  def index
```

2021-06-03 20:22 UTC, manastyretskyi commented on app/controllers/admin_controller.rb
> +class AdminController < ActionController::Base
думаю цей контролер має бути в неймспейсі адміна, типу `Admin::Dashboard`, чи щось таке

2021-06-03 20:22 UTC, manastyretskyi commented on app/controllers/admin_controller.rb
> +  def index
і цей леяут треба прописати в базовому контролері адмін скоупа

2021-06-03 20:22 UTC, manastyretskyi commented on app/views/admin/shared/_content.html.slim
> +              input name="" placeholder=("Find organization...") type="input" /
Що це таке, для чого воно?

2021-06-03 20:22 UTC, manastyretskyi commented on app/views/admin/shared/_navbar.html.slim
> +    img[src="https://i.ibb.co/McTWtRr/giftify.png" class="logo-admin_layout" alt="giftify"]
знову посилання на якийсь сторонній ресурс

2021-06-03 20:22 UTC, manastyretskyi commented on app/views/admin/index.html.slim
> += render partial: 'static_pages/header'
пропиши хедер і футер в леяуті, щоб не треба було його потім всюди додавати

2021-06-03 20:22 UTC, manastyretskyi commented on app/views/admin/shared/_footer.html.slim
> +            |  giftify@gmail.com
`mail_to`?

2021-06-03 20:22 UTC, manastyretskyi commented on app/helpers/public_pages_helper.rb
> +               {name: "Serhii",last_name: "Posternak", avatar: "serhii.png"}]
видали це якщо його більше не треба

2021-06-03 20:22 UTC, manastyretskyi commented on config/routes.rb
> +  get '/admin', to: 'admin#index'
уже писав, напишу ще раз, зроби це як root to: 'admin#index' в середині нейспейсу адміна

2021-06-03 20:22 UTC, manastyretskyi commented on package.json
>      "@rails/actioncable": "^6.0.0",
^^^

2021-06-03 20:58 UTC, MantaPrograming commented on app/views/admin/shared/_content.html.slim
> +              input name="" placeholder=("Find organization...") type="input" /
щоб супер адмін бачив кількість організацій і пошук по ним, щоб адмін бачив кількість юзерів своєї орг і пошук юзера

2021-06-03 21:10 UTC, MantaPrograming commented on config/routes.rb
> +  get '/admin', to: 'admin#index'
поправив

2021-06-03 21:10 UTC, MantaPrograming commented on app/views/admin/shared/_footer.html.slim
> +            |  giftify@gmail.com
поправив

2021-06-03 21:10 UTC, MantaPrograming commented on app/views/admin/index.html.slim
> += render partial: 'static_pages/header'
поправив

2021-06-03 21:10 UTC, MantaPrograming commented on app/views/admin/shared/_navbar.html.slim
> +    img[src="https://i.ibb.co/McTWtRr/giftify.png" class="logo-admin_layout" alt="giftify"]
видалив цей паршал

2021-06-04 08:16 UTC, matsevich commented on spec/requests/admin/admin_layout_spec.rb
> +    expect(response)
this line for what here?

2021-06-04 08:20 UTC, matsevich commented on spec/requests/admin/admin_layout_spec.rb
> +    expect(response)
maybe you forget to write it to the end? `expect(response).to render_template('index')` or else...

2021-06-04 09:23 UTC, manastyretskyi commented on app/controllers/admin/base_controller.rb
>    before_action :require_superadmin
спочатку біфор екшени, потім все інше

2021-06-04 09:23 UTC, manastyretskyi commented on app/controllers/admin_controller.rb
> +  layout "admin"
цей контролер має наслідуватися від `Admin::BaseController`, і тоді тут не треба буде цього

2021-06-04 09:23 UTC, manastyretskyi commented on app/views/admin/admin/index.html.slim
> += render partial: 'admin/shared/footer'
хедер і футер перемісти в леяут, щоб не треба було всюди писати одне і те ж

2021-06-04 09:23 UTC, manastyretskyi commented on app/views/admin/shared/_content.html.slim
> +              input name="" placeholder=("Find organization...") type="input" /
Якщо я щось напишу в то поле, то на сайті щось зміниться?

2021-06-04 09:23 UTC, manastyretskyi commented on app/views/admin/shared/_content.html.slim
> +        - @organizations.last(6).each do |organization|
додай якийсь скоуп з ордерінгом, і використай `limit`

2021-06-04 09:23 UTC, manastyretskyi commented on app/views/admin/shared/_footer.html.slim
> +            a.t-decor.tc href="giftify@gmail.com" giftify@gmail.com
`mail_to` ?

2021-06-04 09:23 UTC, manastyretskyi commented on spec/requests/admin/admin_layout_spec.rb
> +  end
```suggestion
RSpec.describe "Render admin layout", :type => :request do
  it "Must render admin layout, get response" do
    get "/admin"
 
    expect(response).to have_http_status(:success)
    expect(response.body).to include("<h2>Menaging organizations</h2>")
  end
```

2021-06-04 10:07 UTC, vasya539 commented on app/javascript/stylesheets/admin.scss
> +$admin-purple: #734dbb;
винесіть всі кольора в щось накшталт shared/colors.scss і імпортуйте там де вам потрібно

2021-06-04 10:08 UTC, vasya539 commented on app/javascript/stylesheets/admin.scss
> +.bgc{
назви класів робіть зрозуміліше, не скупіться на букви

2021-06-04 10:41 UTC, manastyretskyi commented on app/views/admin/shared/_content.html.slim
> +        - @organizations.order(id: :desc).limit(6).each do |organization|
зроби скоуп ordered в організації

2021-06-04 11:11 UTC, vmyts539 commented on app/javascript/stylesheets/admin.scss
> +  text-decoration: none;
ви юзаєте бустрап, для чого тобі власні класи які роблять те саме?

2021-06-04 11:11 UTC, vmyts539 commented on app/javascript/stylesheets/admin.scss
> +  border-color:white;
слідкуйте за відступами, поставте собі розширення яке буде це робити за вас якщо самі неуважні

2021-06-04 11:11 UTC, vmyts539 commented on app/javascript/stylesheets/admin.scss
> +  background-color: #7148ad;
кольора в змінну і у відповідний файл

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/admin/index.html.slim
> +  .row.flex-nowrap
тут виглядає як щось що так не мало б бути, покажи яку саме проблему ти тут вирішуєш цим flex-nowrap

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_content.html.slim
> +      .col.d-block
для чого на col d-block?

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_content.html.slim
> +        - @organizations.order(id: :desc).limit(6).each do |organization|
в паршал інстанс вари передавайте через локалі
render "admin/shared/content" organizations: @organizations.order.limit
order i limit перенести взагалі в контролер, якщо звісно ти не використовуєш @organizations ще десь де тобі треба інші умови

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_content.html.slim
> +    h2 Menaging organizations
managing

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_content.html.slim
> +                  = image_tag(organization.logo,class: 'img-fluid img-organization rounded-circle z-depth-1 shadow bg-body rounded')
форматування коду, відступ після коми

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_developers.html.slim
> +- developers = [{name: "Mykhailo",last_name: "Vasylenchuk", avatar: "misha.png"},
винеси в модель і тримай там в константі
DEVELOPERS = ...

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_developers.html.slim
> +          - developers.each do |developer|
тоді тут User::DEVELOPERS.each

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_footer.html.slim
> +            i.fas.fa-home.footer-text.me-3
використовуй гем для іконок fontawesome

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_footer.html.slim
> +  .text-center.tc.footer-color-bg.p-4
цього тексту на скріншоті взагалі не видно

2021-06-04 11:11 UTC, vmyts539 commented on app/views/admin/shared/_sidebar.html.slim
> +        a.nav-link.align-middle.px-0[href="/"]
юзай link_to на всі посилання

2021-06-04 11:11 UTC, vmyts539 commented on db/seeds.rb
>  User.all.each do |user|
зроби трейт для факторі юзера with_organization

2021-06-04 11:36 UTC, manastyretskyi commented on app/models/organization.rb
> +  scope :ordered, ->{order(id: :desc).limit(6)}
ліміта тут не треба

2021-06-04 11:45 UTC, MantaPrograming commented on app/models/organization.rb
> +  scope :ordered, ->{order(id: :desc).limit(6)}
через пагінацію вивід обмежити?

2021-06-04 11:47 UTC, vmyts539 commented on app/models/organization.rb
> +  scope :ordered, ->{order(id: :desc).limit(6)}
> через пагінацію вивід обмежити?

а якщо ти захочеш всі організації вивести? будеш створювати ще один скоуп де не буде ліміта? додавай ліміт в контролері, @org = Org.ordered.limit(6) чи як там тобі вже треба

2021-06-04 13:46 UTC, manastyretskyi commented on app/views/admin/shared/_developers.html.slim
> +- developers = [{name: "Mykhailo",last_name: "Vasylenchuk", avatar: "misha.png"},
Не треба там цього в моделі, воно буде тільки тут і все, просто лишній код в моделі буде

2021-06-04 13:47 UTC, manastyretskyi commented on app/views/admin/shared/_footer.html.slim
> +            i.fas.fa-home.footer-text.me-3
та не треба, най уже буде через вебпакер

2021-06-04 13:47 UTC, manastyretskyi commented on app/views/admin/shared/_footer.html.slim
> +            i.fas.fa-home.footer-text.me-3
та не треба, хай уже буде через вебпакер

2021-06-07 13:17 UTC, igorkasyanchuk commented on app/controllers/admin/organizations_controller.rb
> +    @time = Time.new
забрати

2021-06-09 17:13 UTC, manastyretskyi commented on app/javascript/stylesheets/application.scss
> +@import "account/admin";
не треба стилі адмінки інклудити в весь аплікейшин, зроби файлик по анології до `application.scss`, але суто для стилів адмінки, і заінклудь його в леяут адмінки

2021-06-09 17:13 UTC, manastyretskyi commented on app/javascript/stylesheets/header.scss
> +}}}
щось у тебе тут не добре

2021-06-09 17:14 UTC, manastyretskyi commented on app/models/organization.rb
> +  scope :ordered, ->{order(id: :desc)}
форматування поправ

2021-06-09 17:14 UTC, manastyretskyi commented on app/views/admin/shared/_footer.html.slim
> +            =link_to root_url, class: "text-decoration-none text-white"  do
додавай пробіли перед `=`

2021-06-09 17:15 UTC, manastyretskyi commented on app/views/admin/shared/_footer.html.slim
> +            a.text-reset.t-decor href="giftify@gmail.com" giftify@gmail.com
зроби `mail_to`, пишу уже раз четвертій

2021-06-09 17:15 UTC, manastyretskyi commented on app/views/admin/shared/_header.html.slim
> +        form.d-flex
що це за форма?

2021-06-09 17:16 UTC, manastyretskyi commented on app/views/admin/shared/_header.html.slim
> +          input#form1.form-control.bg-light placeholder="Search..." type="search" /
забери інпут цей, він нічого не робить

2021-06-09 17:16 UTC, manastyretskyi commented on app/views/admin/shared/_header.html.slim
> +          input#form1.form-control.bg-light placeholder="Search..." type="search" /
коли комусь треба буде там інпут, він його додасть хвилин за п'ять, не треба на перед додавати лишні і неробочі речі

2021-06-09 17:19 UTC, manastyretskyi commented on app/views/layouts/admin.html.slim
> +    = stylesheet_pack_tag 'account/account', media: 'all', 'data-turbolinks-track': 'reload'
цей код робочий? такого файлу як `account/account` ніби немає

2021-06-09 17:19 UTC, manastyretskyi commented on db/seeds.rb
> +user.role.update(role: Role::SUPERADMIN)
для чого тут ще одного суперадміна створювати?

2021-06-09 18:56 UTC, MantaPrograming commented on app/views/layouts/admin.html.slim
> +    = stylesheet_pack_tag 'account/account', media: 'all', 'data-turbolinks-track': 'reload'
поправив

2021-06-09 18:56 UTC, MantaPrograming commented on db/seeds.rb
> +user.role.update(role: Role::SUPERADMIN)
забрав, в мене вітка стара коли зливав незамітив цього, виправив

2021-06-09 18:57 UTC, MantaPrograming commented on app/views/admin/shared/_header.html.slim
> +          input#form1.form-control.bg-light placeholder="Search..." type="search" /
прибрав

2021-06-09 18:57 UTC, MantaPrograming commented on app/views/admin/shared/_header.html.slim
> +        form.d-flex
прибрав

2021-06-09 19:01 UTC, MantaPrograming commented on app/views/admin/shared/_footer.html.slim
> +            a.text-reset.t-decor href="giftify@gmail.com" giftify@gmail.com
виправив

2021-06-09 19:03 UTC, MantaPrograming commented on app/views/admin/shared/_footer.html.slim
> +            =link_to root_url, class: "text-decoration-none text-white"  do
виправив

2021-06-09 19:04 UTC, MantaPrograming commented on app/models/organization.rb
> +  scope :ordered, ->{order(id: :desc)}
прибрав, вже не потрібно скоупа цього

2021-06-09 19:12 UTC, MantaPrograming commented on app/javascript/stylesheets/header.scss
> +}}}
то код Васі коли він хедер робив

2021-06-09 19:34 UTC, MantaPrograming commented on app/javascript/stylesheets/application.scss
> +@import "account/admin";
зробив працює, але не знаю чи правельно)

2021-06-09 19:50 UTC, manastyretskyi commented on app/javascript/stylesheets/header.scss
> +}}}
ну тут не діло в тому чий це код, а в тому що він не ок, це треба поправити, форматування і все інше

2021-06-09 19:50 UTC, manastyretskyi commented on app/javascript/packs/application.js
> +
чому тут стільки пустих строк у верху?

2021-06-09 19:53 UTC, manastyretskyi commented on app/javascript/packs/application.js
> +import "../stylesheets/account/admin";
зробити в папці `packs` новий пак `account.js`, там заінклудай все що суто для адмінки буде, і його заінклудай в леяут для адмінки

2021-06-09 19:54 UTC, manastyretskyi commented on app/views/admin/admin/index.html.slim
> +
для чого цих всіх пустих строк?

2021-06-09 19:55 UTC, manastyretskyi commented on app/views/admin/shared/_content.html.slim
> +    p| _content
воно тобі те що треба виводить?

2021-06-09 20:05 UTC, MantaPrograming commented on app/views/admin/shared/_content.html.slim
> +    p| _content
так, це просто текст в параграфі що сюда паршал контент рендериться

2021-06-09 20:06 UTC, MantaPrograming commented on app/views/admin/shared/_content.html.slim
> +    p| _content
прибрав

2021-06-09 21:16 UTC, VasylenchukMischa commented on Gemfile
> +
Навіщо пробіл?

2021-06-09 21:17 UTC, MantaPrograming commented on Gemfile
> +
забрав

2021-06-10 06:12 UTC, manastyretskyi commented on app/views/admin/shared/_footer.html.slim
> +      | Softserve.com
`softserveinc.com`)

2021-06-10 06:12 UTC, manastyretskyi commented on app/views/layouts/admin.html.slim
> +        .col-xl-3.col-lg-3.col-md-3.col-sm-12.col-xs-12
чому тут 4 пробіла?

2021-06-10 06:13 UTC, manastyretskyi commented on app/views/layouts/admin.html.slim
> +    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
```suggestion
    = stylesheet_pack_tag 'account', media: 'all', 'data-turbolinks-track': 'reload'
```

2021-06-10 06:13 UTC, manastyretskyi commented on package.json
> -    "@rails/ujs": "^6.0.0",
чому ти їх всіх видалив?

2021-06-10 10:13 UTC, igorkasyanchuk commented on app/views/admin/index.html.slim
> +.container-fluid.mt-2.mb-2
що це за вьюшка

2021-06-10 10:13 UTC, igorkasyanchuk commented on app/views/admin/admin/index.html.slim
> + = render partial: 'admin/shared/content'
а це що за вьюшка що тут за паргал рендериться

2021-06-10 10:13 UTC, igorkasyanchuk commented on app/views/admin/index.html.slim
> +      = render partial: 'admin/shared/content'
чого ти всюди той контент рендериш

і чому сайдбар тут а не в лайауті

2021-06-10 10:14 UTC, igorkasyanchuk commented on app/views/layouts/admin.html.slim
> +    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
а тобі треба application ? підключати тут?
може хай тут будуть суто адмінські стилі

2021-06-10 10:15 UTC, igorkasyanchuk commented on app/views/static_pages/_header.html.slim
> +nav.navbar.navbar-expand-lg.navbar-light
перенеси це в views/shared/_header

2021-06-10 10:33 UTC, MantaPrograming commented on app/views/admin/admin/index.html.slim
> + = render partial: 'admin/shared/content'
з цеї в'юшки рендериться в yield, який в admin layout (body)

2021-06-10 10:34 UTC, MantaPrograming commented on app/views/admin/index.html.slim
> +.container-fluid.mt-2.mb-2
прибрав, її немає бути

2021-06-10 11:02 UTC, manastyretskyi commented on app/views/layouts/admin.html.slim
> +    = javascript_pack_tag 'account', 'data-turbolinks-track': 'reload'
чому ти забрав `stylesheet_link_tag`?

2021-06-10 11:02 UTC, manastyretskyi commented on app/views/layouts/admin.html.slim
> +    = javascript_pack_tag 'account', 'data-turbolinks-track': 'reload'
я казав змінити `stylesheet_pack_tag`, але не казав лінк тег забирати

2021-06-10 11:04 UTC, manastyretskyi commented on app/views/shared/_header.html.slim
> +        button.btn.btn-outline-success.nav-btn type="submit"  Login
чому кнопки, а не лінки, і чому воно однакове для залогінених, і не залогінених?

2021-06-10 11:06 UTC, manastyretskyi commented on app/views/admin/admin/index.html.slim
> + = render partial: 'admin/shared/content'
тут питання в тому де воно рендериться, а чому ввесь контент в'юшки в паршиалі?

2021-06-10 11:18 UTC, MantaPrograming commented on app/views/admin/admin/index.html.slim
> + = render partial: 'admin/shared/content'
поправив, забрав той паршал. Все працює

![Screenshot from 2021-06-10 14-17-52](https://user-images.githubusercontent.com/77298656/121516310-bcb44280-c9f6-11eb-977b-0270c9a4acac.png)

2021-06-10 11:19 UTC, MantaPrograming commented on app/views/shared/_header.html.slim
> +        button.btn.btn-outline-success.nav-btn type="submit"  Login
поправив

2021-06-10 11:50 UTC, manastyretskyi approved these changes

2021-06-10 11:54 UTC, VasylenchukMischa approved these changes

2021-06-11 07:45 UTC, merged