added and styled sidebar layout, generated controller for public page…
IF-122-Ruby/giftify pull request #12
Opened 2021-05-27 14:59 UTC by dimk0o

2021-05-27 15:07 UTC, VasylenchukMischa commented on config/routes.rb
> +  end
прибери цей роут, Діана його робила

2021-05-27 15:08 UTC, VasylenchukMischa commented on app/views/public_pages/home.html.erb
> +</html>
видали цей файл, його Діана створила

2021-05-27 15:08 UTC, VasylenchukMischa reviewed
ну ми мали б писати в слімі

2021-05-28 07:18 UTC, everlastroman approved these changes

2021-05-28 11:08 UTC, manastyretskyi commented on .idea/inspectionProfiles/Project_Default.xml
> +</component>
цього файлу тут треба?

2021-05-28 11:09 UTC, manastyretskyi commented on app/views/layouts/_header.html.slim
> +.sidebar
краще в шаред його перемістити

2021-05-28 11:09 UTC, manastyretskyi commented on app/views/layouts/application.html.erb
> +    <script src="https://kit.fontawesome.com/9b904dfdca.js" crossorigin="anonymous"></script>
це не ок, підключи через гем, або через вебпакер

2021-05-28 11:10 UTC, manastyretskyi commented on app/views/layouts/application.html.erb
> +  <%= render 'layouts/header' %>
перероби цей файл в slim формат

2021-05-28 11:10 UTC, manastyretskyi commented on package.json
> +    "popper.js": "^1.16.1",
?

2021-06-02 15:01 UTC, igorkasyanchuk commented on app/views/layouts/application.html.slim
> +
А чого ті теги видалив

2021-06-02 15:02 UTC, igorkasyanchuk commented on spec/requests/public_pages_spec.rb
> +  end
Ну а тест де? Ти додав нові вьюхи а тест де?

2021-06-02 17:01 UTC, dimk0o commented on app/views/layouts/application.html.slim
> +
через мердж конфлікти

2021-06-03 06:25 UTC, manastyretskyi commented on .idea/giftify.iml
>      <orderEntry type="library" scope="PROVIDED" name="activerecord (v6.1.3.2, rbenv: 2.7.2) [gem]" level="application" />
видали цей файл

2021-06-03 06:34 UTC, manastyretskyi requested changes

2021-06-03 06:34 UTC, manastyretskyi commented on app/javascript/packs/application.js
> +
для чого тут дві пусті строки?

2021-06-03 06:34 UTC, manastyretskyi commented on app/javascript/stylesheets/colors.scss
> +$color-purple: #A854A5;
додавайте пусті строки в кінці файлів, пишу уже в шостому ПРі

2021-06-03 06:34 UTC, manastyretskyi commented on app/javascript/stylesheets/header.scss
> +}
для чого це? бутстрап сам ресетає дефолтні браузерні стилі

2021-06-03 06:34 UTC, manastyretskyi commented on app/views/layouts/application.html.slim
> +
ну додай їх назад якщо погано конфлікти порезолвив

2021-06-03 06:34 UTC, manastyretskyi commented on app/views/shared/_header.html.slim
> +      = link_to 'static_pages/home' do
використовуй хелпери для урлів

2021-06-03 06:34 UTC, manastyretskyi commented on config/routes.rb
> +
для чого це тут?

2021-06-03 06:34 UTC, manastyretskyi commented on spec/controllers/static_pages_spec.rb
> +RSpec.describe StaticPagesController, type: :controller do
пиши ріквест спеки замість контролер

2021-06-03 07:34 UTC, dimk0o commented on app/views/shared/_header.html.slim
> +      = link_to 'static_pages/home' do
це заглушка просто

2021-06-03 19:51 UTC, manastyretskyi commented on app/views/layouts/application.html.slim
>      = render "static_pages/header"
а не забагато хередів?

2021-06-04 08:11 UTC, manastyretskyi approved these changes

2021-06-04 08:11 UTC, merged