add namespaces and permit methods
IF-122-Ruby/giftify pull request #14
Opened 2021-05-28 17:11 UTC by VasylenchukMischa

# [Issue title](https://issueurl)

## Changes description
Додано неймспейси, щоб усі могли почати повноцінну роботу над тасками
## Screnshots of the added pages
![image](https://user-images.githubusercontent.com/38836502/120019221-d9ad4680-bff0-11eb-83f4-84834b8e14c4.png)

## Check list:
- [ ] Integration Tests
- [ ] Functional
- [ ] Unit
- [ ] Factories
- [ ] Updated seed file

2021-05-28 17:15 UTC, manastyretskyi commented on app/assets/stylesheets/account/admin/organizations.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
пусті файли видаляй

2021-05-28 17:17 UTC, manastyretskyi commented on app/controllers/application_controller.rb
> +  end
давай краще цим гемом це зроби [pundit](https://github.com/varvet/pundit)

2021-05-28 17:18 UTC, manastyretskyi commented on app/helpers/account/admin/organizations_helper.rb
> +module Account::Admin::OrganizationsHelper
пусті файли видаляй

2021-05-28 17:21 UTC, manastyretskyi requested changes

2021-05-28 17:21 UTC, manastyretskyi commented on config/routes.rb
> +  end
це трохи не те, з цим не буде зручно працювати просто
```suggestion
  namespace :account do
    resources :users, only: [:index, :show]
  end
  
  namespace :admin do
    resources :organizations, only: [:index, :show]
  end
```

2021-05-28 17:21 UTC, manastyretskyi commented on app/controllers/account/admin/organizations_controller.rb
> +class Account::Admin::OrganizationsController < Account::Admin::AdminsController
не треба неймспейс адміна в неймспейс акаунта засовувати

2021-05-28 17:22 UTC, manastyretskyi commented
тестів на контролери немає

2021-05-30 19:25 UTC, manastyretskyi requested changes

2021-05-30 19:25 UTC, manastyretskyi commented on spec/controllers/superadmin/organizations_controller_spec.rb
> +RSpec.describe Superadmin::OrganizationsController, type: :controller do
ми на колі говорили що треба робити ріквест тести, вони кращі ніж контролер ([рандомна стаття про це](https://medium.com/just-tech/rspec-controller-or-request-specs-d93ef563ef11))

2021-05-30 19:25 UTC, manastyretskyi commented on config/routes.rb
> +  namespace :superadmin do
чому не просто `admin`?

2021-05-30 19:25 UTC, manastyretskyi commented on app/views/superadmin/organizations/show.html.slim
> +  li = link_to "Back", admin_organizations_path
додавай `new line` в кінці кожного файла

2021-05-30 19:25 UTC, manastyretskyi commented on app/views/layouts/application.html.erb
> +    <%= alert %>
це треба в паршиал винести, і ще, ніхто флеші так не виводить, бо можна задавати кастомні флеші(не `notice` чи `alert`), і таким способом вони не будуть рендеритися

2021-05-30 19:25 UTC, manastyretskyi commented on app/policies/superadmin/organization_policy.rb
> +class Superadmin::OrganizationPolicy < ApplicationPolicy
думаю не треба писати політику для кожного контролера в скоупі супер адміна, просто зробити одну політику для цілого скоупа, зробити якийсь базовий контролер від якого будуть наслідуватися всі контролери цього скоупа, і додати біфор екшин, і в ньому авторизувати юзера

2021-05-30 19:25 UTC, manastyretskyi commented on app/policies/superadmin/organization_policy.rb
> +class Superadmin::OrganizationPolicy < ApplicationPolicy
Мати окрему політику для кожного контролера буде доречно в скоупі організації, але в скоупі суперадміна це має мало сенсу так як в 99% випадків треба просто перевіряти що він суперадмін

2021-05-30 19:25 UTC, manastyretskyi commented on app/controllers/roots_controller.rb
> +class RootsController < ApplicationController
Назва так собі, краще уже `home`

2021-05-30 19:25 UTC, manastyretskyi commented on app/controllers/application_controller.rb
> +    redirect_to(request.referrer || root_path)
Тут краще використати `redirect_back`

2021-05-30 19:25 UTC, manastyretskyi commented on app/controllers/account/users_controller.rb
> +  end
Робити в кожному контролері цього скоупа таке буде напряжно, і не дуже DRY, може зробити щось типу `current_user`, але для організації?

2021-05-30 19:25 UTC, manastyretskyi commented on app/controllers/superadmin/superadmins_controller.rb
> +class Superadmin::SuperadminsController < ApplicationController
Думаю краще `BaseController`

2021-05-30 19:25 UTC, manastyretskyi commented on app/controllers/superadmin/superadmins_controller.rb
> +class Superadmin::SuperadminsController < ApplicationController
І скоуп напевно якось по іншому назвати

2021-05-30 19:25 UTC, manastyretskyi commented on spec/controllers/account/users_controller_spec.rb
> +  end
Це ви плануєте писати таке в кожному тесті таке?

2021-05-30 19:25 UTC, manastyretskyi commented on spec/controllers/account/users_controller_spec.rb
> +  end
В факторі бот є такі штуки як `trait`, подумай я з їх допомогою можна собі життя трохи спростити

2021-05-30 19:25 UTC, manastyretskyi commented on spec/controllers/account/users_controller_spec.rb
> +    it { expect(subject).to render_template('index') }
це не гуд, вони тестують одне і теж, при тому в різних тесткейсах, для того щоб заранити їх треба буде двічі запустити факторі, і двічі базу почистити, просто трата часу

2021-05-30 19:25 UTC, manastyretskyi commented on spec/controllers/account/users_controller_spec.rb
> +    it { expect(subject).to render_template('show') }
те саме що й вище

2021-05-30 19:25 UTC, manastyretskyi commented on spec/support/devise.rb
> +  config.include Devise::Test::ControllerHelpers, type: :view
В'ю тести ніхто не пише

2021-05-30 19:28 UTC, VasylenchukMischa commented on app/controllers/roots_controller.rb
> +class RootsController < ApplicationController
Цей контролер пишуть інші, я для тесту додав

2021-05-31 15:07 UTC, manastyretskyi requested changes

2021-05-31 15:07 UTC, manastyretskyi commented on Gemfile
> +  # gem 'rails-controller-testing'
якщо цього більше не треба - видаляй

2021-05-31 15:07 UTC, manastyretskyi commented on Gemfile.lock
> +      activesupport (>= 5.0.1.rc1)
в гемфайлі ти його закоментив, а бандл не заранив

2021-05-31 15:07 UTC, manastyretskyi commented on app/controllers/account/accounts_controller.rb
> +end
```suggestion
  private

  def current_organization
    @current_organization ||= current_user.organization
  end
end

```

2021-05-31 15:07 UTC, manastyretskyi commented on app/controllers/account/accounts_controller.rb
> +  # before_action :current_organization
якщо не треба, видаляй

2021-05-31 15:07 UTC, manastyretskyi commented on app/controllers/account/users_controller.rb
> +    @users = current_organization.users.all
я б цих юзерів зробив як рілейшин юзера, щось типу `colleagues`, просто у всіх юзерів є організація, відповідно є люди з якими він працює

2021-05-31 15:07 UTC, manastyretskyi commented on app/controllers/application_controller.rb
> +    redirect_back(fallback_location: root_path)
```suggestion
    flash[:alert] = "You are not authorized to perform this action."
  
    redirect_back(fallback_location: root_path)
```

2021-05-31 15:07 UTC, manastyretskyi commented on app/controllers/homes_controller.rb
> +end
```suggestion
end

```

2021-05-31 15:07 UTC, manastyretskyi commented on app/views/admin/organizations/show.html.slim
> +  li = link_to "Back", admin_organizations_path
```suggestion
  li = link_to "Back", admin_organizations_path

```

2021-05-31 15:07 UTC, manastyretskyi commented on spec/factories/user.rb
> +      end
може зразу ставити роль суперадмін?

2021-05-31 15:07 UTC, manastyretskyi commented on spec/factories/user.rb
> +    trait :with_superadmin_role do
```suggestion
    trait :superadmin do
```

2021-05-31 15:07 UTC, manastyretskyi commented on spec/factories/user.rb
> +    trait :with_admin_role do
```suggestion
    trait :admin do
```

2021-05-31 15:07 UTC, manastyretskyi commented on spec/factories/user.rb
> +    trait :with_user_role do
```suggestion
    trait :simple do
```

2021-05-31 17:43 UTC, manastyretskyi commented on spec/policies/account/user_policy_spec.rb
> +  subject { described_class }
```suggestion
  let(:admin) { FactoryBot.create(:user, :admin) }

  subject { described_class }
```

2021-06-01 06:29 UTC, manastyretskyi commented on spec/requests/account/users_controller_spec.rb
> +  let(:admin) { FactoryBot.create(:user, :admin) }
У вас здається заінклуджені хелпери факторі бота, тому можна просто так
```suggestion
  let(:admin) { create(:user, :admin) }
```

2021-06-01 06:29 UTC, manastyretskyi commented on spec/policies/admin/organization_policy_spec.rb
> +  let(:superadmin) { FactoryBot.create(:user, :superadmin) }
Те саме що й вище

2021-06-01 06:29 UTC, manastyretskyi commented on spec/factories/user.rb
> +      role { Role.new(organization: organization, role: Role::SUPERADMIN) }
```suggestion
      role { build(role: :superadmin) }
```

2021-06-01 06:29 UTC, manastyretskyi commented on spec/factories/user.rb
> +      role { Role.new(organization: organization, role: Role::ADMIN) }
```suggestion
      role { build(role: :admin) }
```

2021-06-01 06:33 UTC, VasylenchukMischa commented on spec/factories/user.rb
> +      role { Role.new(organization: organization, role: Role::ADMIN) }
Так не працює, потрібно ж ще асоціації з організацією

2021-06-01 06:33 UTC, VasylenchukMischa commented on spec/factories/user.rb
> +      role { Role.new(organization: organization, role: Role::ADMIN) }
![image](https://user-images.githubusercontent.com/38836502/120277178-65a6c300-c2bc-11eb-88b2-63e08784f1ab.png)

2021-06-01 08:21 UTC, merged