implamentation crud for user in account namespace
IF-122-Ruby/giftify pull request #15
Opened 2021-06-01 21:02 UTC by SofiiaHlushchak

# [Issue title](https://issueurl)

## Changes description

## Screnshots of the added pages

## Check list:
- [ ] Integration Tests
- [* ] Functional
- [* ] Unit
- [ ] Factories
- [ ] Updated seed file

2021-06-02 07:32 UTC, mdotvasylenchuk commented on app/controllers/account/users_controller.rb
> +    @user = resource
Напевно краще написати callback, якось не дуже DRY

2021-06-02 07:39 UTC, vikdotdev commented on app/controllers/account/users_controller.rb
> +    @user = resource
колбеком робити то є валідний спосіб але ми переважно робим так як тут зроблено, маленький конвеншн -  `resource`, `collection` і асайнимо у екшенах явно

2021-06-02 07:44 UTC, vikdotdev commented on spec/requests/account/users_controller_spec.rb
> +  let(:new_user)       { create(:user, :admin) }
тут трохи недобре

варто поскладати у цей дескрайб тільки те що юзається у всіх тестах, все що спеціфічне до скажем 
`PUT #update` складаєм у відповідний блок;

2021-06-02 07:45 UTC, vikdotdev commented on spec/requests/account/users_controller_spec.rb
>    describe "users" do
цей блок нічого корисного не додає

2021-06-02 07:46 UTC, vikdotdev commented on spec/requests/account/users_controller_spec.rb
> +    it '#show' do
замість `it` тут пишемо тако
```
   describe "GET #show" do
      # ... appropriate let setup here
      it "has status success" do
         # spec body
      end
   end
```

2021-06-02 07:47 UTC, manastyretskyi commented on app/controllers/account/users_controller.rb
>    end
це не ок, `current_user` по дефолту передається в усі політики, а об'єкт який ти тут передаєш, це об'єкт по відношенню до якого ця політика буде примінятися, припустимо що ти хочеш щоб юзер міг едітати тільки сам себе, з цим кодом політика буде примінятися завжди до теперішнього юзера, і він зможе едітати інших юзерів

2021-06-02 07:47 UTC, manastyretskyi commented on app/models/user.rb
> +  accepts_nested_attributes_for :role, allow_destroy: true
для чого тут `allow_destroy: true`?

2021-06-02 07:48 UTC, vikdotdev commented on spec/requests/account/users_controller_spec.rb
> +    it '#show' do
таким чином спек має чіткий меседж, шось типу Account::UsersController GET#show has status success

2021-06-02 07:49 UTC, vikdotdev commented on spec/requests/account/users_controller_spec.rb
> +    end
аналогічно з рештою - обгортаєм у дескрайб, у цьому дескрайбі робим сетап, а у `it` блоці пишем тільки перевірку

2021-06-02 07:50 UTC, vikdotdev commented on config/routes.rb
> +    resources :users, expect: [:create, :new]
except ?

2021-06-02 09:02 UTC, matsevich commented on app/controllers/account/users_controller.rb
> +    @user = resource
why you don't write these rows `@user = resource` within before_action for all the actions where it used?

2021-06-02 09:02 UTC, matsevich commented on app/views/account/users/_form.html.slim
> +    = role.input :role, autofocus: true
user must write down his role by letters? don't you want to use some collection_select or something similar?

2021-06-02 09:08 UTC, VasylenchukMischa commented on app/controllers/account/users_controller.rb
> +    @user = resource
Please, read first comment to this pull request, Victor explained this point

2021-06-02 09:20 UTC, SofiiaHlushchak commented on app/controllers/account/users_controller.rb
>    end
Це не мій код

2021-06-02 09:24 UTC, manastyretskyi commented on app/controllers/account/users_controller.rb
>    end
Ну нічого, код не робочий, треба поправити

2021-06-02 10:39 UTC, igorkasyanchuk commented on app/controllers/account/users_controller.rb
> +    @user = resource
Не треба before action, це не зручно, хай буде як є

2021-06-02 10:40 UTC, igorkasyanchuk commented on app/controllers/account/users_controller.rb
> +    @user = resource
Ага не треба колбека, потім не треба бігати по коду і шукати де там ті змінні ініціалізуються

2021-06-02 10:42 UTC, igorkasyanchuk commented on app/models/user.rb
>    has_one :owned_organization, class_name: 'Organization'
А що це за зв'язок на роль, зжаєтсья ж не так мало бути. В тій таблиці що юзери і організації там колонка з роллю має бути

2021-06-02 10:42 UTC, igorkasyanchuk commented on app/views/account/users/edit.html.slim
> += render 'form'
Пишіть повний шлях до паршала для зручності

2021-06-02 10:46 UTC, VasylenchukMischa commented on app/models/user.rb
>    has_one :owned_organization, class_name: 'Organization'
так і є, у нас окрема модель Role, через яку зв'язуються юзери і організації

2021-06-02 18:03 UTC, manastyretskyi commented on app/views/account/users/_form.html.slim
> +    = f.submit
додавай пустий рядочок в кінці файлів

2021-06-02 18:05 UTC, manastyretskyi commented on spec/requests/account/users_controller_spec.rb
> +  let(:admin_id)       { admin.id }
чому тут такі відступи між `)` i `{`?

2021-06-02 18:05 UTC, manastyretskyi commented on spec/requests/account/users_controller_spec.rb
>        get '/account/users'
використай хелпер для урлів

2021-06-02 18:06 UTC, manastyretskyi commented on spec/requests/account/users_controller_spec.rb
> +      expect do
```suggestion
    it 'should destroy users from admin`s organization' do
      expect do
```

2021-06-02 18:09 UTC, manastyretskyi commented on app/controllers/account/users_controller.rb
> +    authorize([:account, :user])
це не ок, так ти не будеш знати до чого приміняється політика, не треба лінитись в [доки](https://github.com/varvet/pundit#policies) заходити

2021-06-02 18:11 UTC, manastyretskyi commented on spec/requests/account/users_controller_spec.rb
> +  let(:admin_id)       { admin.id }
це `admin_id` ніде не використовується, його тут не треба

2021-06-03 10:28 UTC, matsevich commented on spec/requests/account/users_controller_spec.rb
> +    let(:user_params)    { { user: { first_name: new_admin_name, last_name:  'Last name Admin' } } }
you can use `attributes_for :user` instead of `{ user: { first_name: new_admin_name, last_name: 'Last name Admin' } }`

2021-06-03 14:16 UTC, manastyretskyi commented on app/controllers/account/users_controller.rb
> +                                  role_attributes: %i[id role])
а це айді тут точно треба?

2021-06-03 15:34 UTC, igorkasyanchuk commented on app/views/account/users/_form.html.slim
> +    = role.input :role, collection: Role::roles.except(:superadmin), include_blank: false
А якщо я в параметрах вишлю суперадмін значення. Розумієш про що я? Задам черёд хром інше значення і зроблю запит

2021-06-03 16:24 UTC, manastyretskyi requested changes

2021-06-03 16:24 UTC, manastyretskyi commented on app/controllers/account/users_controller.rb
> +        format.json { render json: @user.errors, status: :unprocessable_entity }
а цей формат `json` тут точно треба, для чого вам зараз це?

2021-06-03 16:24 UTC, manastyretskyi commented on app/models/user.rb
> +  accepts_nested_attributes_for :role
додай [reject_if: :all_blank](https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#method-i-accepts_nested_attributes_for)

2021-06-03 19:33 UTC, igorkasyanchuk approved these changes

2021-06-03 19:36 UTC, everlastroman approved these changes

2021-06-03 19:42 UTC, SashaDi13 approved these changes

2021-06-03 19:46 UTC, manastyretskyi approved these changes

2021-06-03 19:46 UTC, merged