add column to feedback, change static_pages controller(add feedback a…
IF-122-Ruby/giftify pull request #16
Opened 2021-06-02 11:20 UTC by everlastroman

…ctions), seeds, rspec test for static_pages controller

# [Issue title](https://issueurl)
 add functionality for creating feedbacks and save valid data to db
## Changes description
-add new column to feedback model (is_read). Now the admin can see if the feedback is read
-add and styling form for feedback
-add routes
-add request tests
-add actions "get" and "post" in controller "static_pages" for feedbacks
## Screnshots of the added pages
Form:
![image](https://user-images.githubusercontent.com/24572256/120471330-4045b200-c3ad-11eb-8363-fe749229861c.png)
Invalid data:
![image](https://user-images.githubusercontent.com/24572256/120471437-60757100-c3ad-11eb-9fb5-d8f44187adf4.png)
success create feedback:
![image](https://user-images.githubusercontent.com/24572256/120471662-a599a300-c3ad-11eb-9f90-4e6e75f063c3.png)

## Check list:
- [ ] Integration Tests
- [.] Functional
- [.] Unit
- [ ] Factories
- [.] Updated seed file

2021-06-02 11:40 UTC, igorkasyanchuk commented on app/controllers/static_pages_controller.rb
> +
Не гуд, забери це. Токен має перевірятись

2021-06-02 11:42 UTC, igorkasyanchuk commented on app/javascript/stylesheets/feedback_form.scss
> +abbr[title="required"] {
Якщо ці стилі про фідбек то чому глобально ти міняєш abbr стиль. Винеси в загальні якісь стилі

2021-06-02 11:42 UTC, igorkasyanchuk commented on app/javascript/stylesheets/feedback_form.scss
> +    margin-left: 1em;
Форматування
Скільки пробєлів має бути

2021-06-02 11:43 UTC, everlastroman commented on app/controllers/static_pages_controller.rb
> +
> Не гуд, забери це. Токен має перевірятись

Якщо я забираю, то отримую помилку від одного з методів Devise. Я з Любчиком говорив, то він казав якщо рішення не знайду залишати. Я так розумію що проблема в тому що фідбеки можуть писати і не зареєстровані користувачі, тому гем девайс і викликає помилку

2021-06-02 11:44 UTC, igorkasyanchuk commented on app/views/static_pages/_form.html.slim
> +  = simple_form_for @feedback, url:'contact_us', method: :post do |f|
Що це за юрл такий, хай буде не строка а рубішний метод contact_us_path

2021-06-02 11:44 UTC, igorkasyanchuk commented on app/views/static_pages/_header.html.slim
> +    a.nav-link.text_color href="contact_us"  Contact Us
Юзай рельси

2021-06-02 11:44 UTC, igorkasyanchuk commented on config/routes.rb
> +  get 'contact_us', action: :contact_us, controller: 'static_pages'
Ресорсес онлі

2021-06-02 11:44 UTC, everlastroman commented on app/controllers/static_pages_controller.rb
> +
Один фідбек створюється але коли створюю наступний виникає помилка, чищу кеш браузера і тільки тоді створюється другий фідбек

2021-06-02 11:45 UTC, manastyretskyi commented on app/views/static_pages/_form.html.slim
> +  = simple_form_for @feedback, url:'contact_us', method: :post do |f|
використай хелпер для урл

2021-06-02 11:45 UTC, manastyretskyi commented on app/views/static_pages/_header.html.slim
> +    a.nav-link.text_color href="contact_us"  Contact Us
в рельсів є хелпер для посилань `link_to`

2021-06-03 06:12 UTC, manastyretskyi commented on app/controllers/feedbacks_controller.rb
> +class FeedbacksController < ApplicationController
Немає такого як `feedbacks`)

2021-06-03 06:26 UTC, manastyretskyi requested changes

2021-06-03 06:26 UTC, manastyretskyi commented on app/controllers/feedbacks_controller.rb
> +      redirect_to :root, notice: "#{@feedback.name}, thank you for your feedback. The administration will contact you shourtly."
```suggestion
      redirect_to root_path, notice: "#{@feedback.name}, thank you for your feedback. The administration will contact you shourtly."
```

2021-06-03 06:26 UTC, manastyretskyi commented on app/controllers/feedbacks_controller.rb
> +      redirect_to :root, notice: "#{@feedback.name}, thank you for your feedback. The administration will contact you shourtly."
Ще цей флеш трохи не підходящий як на мене, ти залишаєш фідбек і тобі кажуть що з тобою потім сконтактують, для чого?)

2021-06-03 06:26 UTC, manastyretskyi commented on app/javascript/stylesheets/feedback_form.scss
> +}
Писав уже раз 5, додавайте пусті строки в кінці файлів

2021-06-03 06:26 UTC, manastyretskyi commented on app/javascript/stylesheets/style.scss
> +}
глобально такий стиль я б не задавав

2021-06-03 06:26 UTC, manastyretskyi commented on config/routes.rb
> +  resource :feedback, path: :contact_us, only: :create
чому фідбек це `contact_us`?

2021-06-03 06:26 UTC, manastyretskyi commented on config/routes.rb
> +    post 'contact_us', action: :create, controller: 'static_pages'
а для чого?

2021-06-03 06:26 UTC, manastyretskyi commented on db/migrate/20210601094437_add_is_read_to_feedbacks.rb
> +    add_column :feedbacks, :is_read, :boolean, default: false
писати `is_*` це таке собі, краще просто `viewed`

2021-06-03 06:26 UTC, manastyretskyi commented on db/migrate/20210601094437_add_is_read_to_feedbacks.rb
> +    add_column :feedbacks, :is_read, :boolean, default: false
можеш його ще `null: false` зробити

2021-06-03 06:26 UTC, manastyretskyi commented on spec/requests/feedbacks_spec.rb
> +      }}
В факторі бот є така штука `attributes_for`

2021-06-03 13:05 UTC, manastyretskyi commented on app/views/feedbacks/_form.html.slim
> +      .card-header[style="background-color:#734dbb"]
інлайн стилі забери

2021-06-03 13:06 UTC, manastyretskyi commented on app/views/feedbacks/_form.html.slim
> +                                                        ['About partnership','2'],['Other','3']]
Зроби якусь константу в моделі, і звідти бери ці значення

2021-06-03 13:07 UTC, manastyretskyi commented on app/views/feedbacks/_form.html.slim
> +            = f.input :message, label: "Reason: ", placeholder: "Write message ... ", as: :text, :html_input => {:cols => 5, :rows => 15}
а цей `html_input` працює? мені здається що цей параметр називається `input_html`

2021-06-03 13:09 UTC, manastyretskyi commented on db/migrate/20210603104950_rename_feedback_is_read_column.rb
> +    rename_column :feedbacks, :is_read, :viewed
для чого створювати нову міграцію? просто зроби ролбек і стару поедітай

2021-06-03 13:10 UTC, manastyretskyi commented on spec/requests/feedbacks_spec.rb
> +      feedback_params = FactoryBot.attributes_for :feedback
у вас заінклуджені хелпери факторі бота, можна просто так 
```suggestion
      feedback_params = attributes_for :feedback
```

2021-06-03 13:10 UTC, everlastroman commented on db/migrate/20210603104950_rename_feedback_is_read_column.rb
> +    rename_column :feedbacks, :is_read, :viewed
> для чого створювати нову міграцію? просто зроби ролбек і стару поедітай

я спробував, вона чомусь не працювала. Залишити так, чи пробувати ще?

2021-06-03 13:12 UTC, everlastroman commented on app/views/feedbacks/_form.html.slim
> +            = f.input :message, label: "Reason: ", placeholder: "Write message ... ", as: :text, :html_input => {:cols => 5, :rows => 15}
> а цей `html_input` працює? мені здається що цей параметр називається `input_html`

не працює. Пофікшу.

2021-06-03 13:12 UTC, igorkasyanchuk commented on app/javascript/stylesheets/feedback_form.scss
> +  abbr[title="required"] {
А чого ховати, хай будуть червоним щоб видно було які поля обов'язкові
І винеси в загальні стилі

2021-06-03 13:14 UTC, igorkasyanchuk commented on app/views/feedbacks/_form.html.slim
> +            = f.input :message, label: "Reason: ", placeholder: "Write message ... ", as: :text, :html_input => {:cols => 5, :rows => 15}
І юзай нові стилі для хешів

2021-06-03 13:14 UTC, everlastroman commented on app/javascript/stylesheets/feedback_form.scss
> +  abbr[title="required"] {
> А чого ховати, хай будуть червоним щоб видно було які поля обов'язкові
> І винеси в загальні стилі

То видно. Пропадає тільки * і ...

2021-06-03 13:14 UTC, igorkasyanchuk commented on app/views/feedbacks/new.html.slim
> += render "form"
Повний шлях до паршалу пропиши

2021-06-03 13:15 UTC, everlastroman commented on app/views/feedbacks/new.html.slim
> += render "form"
> Повний шлях до паршалу пропиши

ок

2021-06-03 13:16 UTC, igorkasyanchuk commented on config/routes.rb
> +  resource :feedback, path: :contact_us, only: :create
Має бути 2 роута там в only - new create

2021-06-03 13:16 UTC, igorkasyanchuk commented on config/routes.rb
> +  resource :feedback, path: :contact_us, only: :create
New_feedback_path юзай і тд

2021-06-03 13:18 UTC, manastyretskyi commented on db/migrate/20210603104950_rename_feedback_is_read_column.rb
> +    rename_column :feedbacks, :is_read, :viewed
Воно точно працює, якщо правильно написати звісно ж

2021-06-03 14:37 UTC, manastyretskyi commented on app/models/feedback.rb
> +            ['About partnership','2'],['Other','3']].freeze
Це масив, має бути множина, і форматування нормальне зроби

2021-06-03 14:37 UTC, manastyretskyi commented on app/models/feedback.rb
> +
для чого ця пуста строка тут?

2021-06-03 14:39 UTC, manastyretskyi commented on app/views/feedbacks/_form.html.slim
> +    .card.m-2
форматування поправ

2021-06-03 14:39 UTC, manastyretskyi commented on config/routes.rb
для чого тут дві пусті строки?

2021-06-03 14:58 UTC, manastyretskyi commented on app/models/feedback.rb
> +  REASONS = ['Want delete organization', 'Find bug', 'About partnership', 'Other'].freeze
Винеси кожеш різон в окрему костанту, і додай валідацію на те що різон в списку доступних

2021-06-03 15:59 UTC, MantaPrograming approved these changes

2021-06-03 16:10 UTC, manastyretskyi approved these changes

2021-06-03 16:11 UTC, merged

2021-06-03 16:11 UTC, DenysVinegod approved these changes