Add about page
IF-122-Ruby/giftify pull request #17
Opened 2021-06-02 13:32 UTC by lbeketl

# [styling static page - ABOUT US](https://trello.com/c/uSS1nJgT/18-styling-static-page-about-us)

## Changes description

## Screnshots of the added pages
![Знімок екрану з 2021-06-02 16-30-33](https://user-images.githubusercontent.com/55595579/120489035-f74b2900-c3bf-11eb-9076-77910df4c4cb.png)

## Check list:
- [ ] Integration Tests
- [ ] Functional
- [ ] Unit
- [ ] Factories
- [ ] Updated seed file

2021-06-02 13:49 UTC, matsevich commented on app/javascript/stylesheets/header.scss
> +  .btn {
is it bootstrap selector? don't override bootstrap styles, just add custom classes and then add styles for them

2021-06-02 13:49 UTC, matsevich commented on app/javascript/stylesheets/header.scss
> +      background: rgb(111,6,131);
add few screenshots with your hover effects

2021-06-02 13:49 UTC, matsevich commented on app/views/static_pages/about_partials/_about-area.html.slim
> +            | Download doc
leave an empty line at the end of all your files

2021-06-02 13:49 UTC, matsevich commented on app/views/static_pages/about_partials/_services-area.html.slim
> +      .row
strange spacing

2021-06-02 13:56 UTC, manastyretskyi requested changes

2021-06-02 13:56 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +$btn_color: linear-gradient(90deg, rgb(111,6,131) 50%, rgb(69,6,131) 100%);
це не колір, а градієнт, для css різниця дуже велика, буде просто людей конфюзити

2021-06-02 13:56 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +  box-shadow: 0 0 20px rgb(59, 58, 61);
щось багато `!important`, такі стилі потім важко оверайдити, а тут він ще й в міксіні

2021-06-02 13:56 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +  .about__title {
```suggestion
  height: 100%;

  .about__title {
```

2021-06-02 13:56 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +  }
краще потратити 1 хв щоб назву придумати і не робити такі глобальні стилі, ніж потім хвилин 30 щоб придумати як змінити чомусь стилі і не поламати всьо решту

2021-06-02 13:56 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +  button {
той самий комент що й вище

2021-06-02 13:56 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +      @include color_btn();
в одному місці `@include color_btn;` а в іншому `@include color_btn();` якось оприділись уже

2021-06-02 13:56 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +    &:hover {
додавай пусті строки між класами, стає набагато читабельніше

2021-06-02 13:56 UTC, manastyretskyi commented on app/views/static_pages/about.html.slim
> +    = render "static_pages/about_partials/about-area"
щось у тебе тут і снейк кейс, і кебаб кейс

2021-06-02 13:56 UTC, manastyretskyi commented on app/views/static_pages/about_partials/_brand-area.html.slim
> +            = image_tag "about/brands/b1.png", size: "250x250"
може цей `size` css-ом зробити?

2021-06-02 13:56 UTC, manastyretskyi commented on app/views/static_pages/about_partials/_services-area.html.slim
> +      .row
чому тут 3-4 таба?

2021-06-02 14:00 UTC, igorkasyanchuk commented on app/javascript/stylesheets/about.scss
> +  h1 {
А можна щоб стилі були якісь однакові на сторінках h1 h2 I td...

2021-06-02 14:01 UTC, igorkasyanchuk commented on app/javascript/stylesheets/about.scss
> +      padding-top: 50px !important;
Щось забагато різних стилів на h2 в різних місцях
Ти ж можеш свої стилі якісь придумати і нові класи нащо h2 I інші юзати

2021-06-02 14:02 UTC, igorkasyanchuk commented on app/javascript/stylesheets/header.scss
> +  .btn {
Тут вони в nav і може норм

2021-06-02 14:03 UTC, igorkasyanchuk commented on app/views/static_pages/about.html.slim
> +    = render "static_pages/about_partials/about-area"
Ага перейменуй файл

2021-06-02 14:04 UTC, igorkasyanchuk commented on app/views/static_pages/about_partials/_brand-area.html.slim
> +        .col-lg-4.col-md-6.col-sm-6
Можеш в циклі вивести ті картинки без копяпаста

2021-06-02 14:05 UTC, igorkasyanchuk commented on config/routes.rb
> +  get 'about', to: 'static_pages#about'
А тест на те що та сторінка працює є?

2021-06-02 14:07 UTC, lbeketl commented on app/javascript/stylesheets/header.scss
> +      background: rgb(111,6,131);
![Знімок екрану з 2021-06-02 17-05-48](https://user-images.githubusercontent.com/55595579/120495044-01bbf180-c3c5-11eb-9e4a-3d447a2da6f6.png)

2021-06-03 06:50 UTC, manastyretskyi requested changes

2021-06-03 06:50 UTC, manastyretskyi commented on app/controllers/static_pages_controller.rb
> +    @brands = ['b1.png', 'b2.jpeg', 'b3.jpeg', 'b4.png', 'b5.png', 'b6.jpeg']
це тут точно лишнє, якщо б назви були різні то можна було б в в'ю локальну змінну задефайнити, але тут це можна просто інтерполяцією в циклі зробити

2021-06-03 06:50 UTC, manastyretskyi commented on spec/requests/static_pages_spec.rb
> +
тут ця пуста строка лишня

2021-06-03 06:50 UTC, manastyretskyi commented on app/views/static_pages/home.html.slim
> +      img.tools src="#"body
що це за `body`?

2021-06-03 06:50 UTC, manastyretskyi commented on app/javascript/stylesheets/about.scss
> +  .about__title {
якщо у батьківського класу немає стилів, то не треба додавати строку між ним і дочірнім класом

2021-06-03 06:50 UTC, manastyretskyi commented on app/javascript/stylesheets/header.scss
> +  li {
спершу мають іти стилі, а потім вкладені класи, а тут стилі десь між вкладеними класами

2021-06-03 09:58 UTC, lbeketl commented on config/routes.rb
> +  get 'about', to: 'static_pages#about'
https://github.com/IF-122-Ruby/giftify/pull/17/files#diff-0c2fcb32d350102e3c555bddd5975683c99a0c2e6043b167c24d807b3b627088R11

2021-06-03 10:07 UTC, matsevich approved these changes

2021-06-03 10:20 UTC, dimk0o approved these changes

2021-06-03 11:47 UTC, manastyretskyi approved these changes

2021-06-03 11:48 UTC, merged