Gifts
IF-122-Ruby/giftify pull request #21
Opened 2021-06-03 21:29 UTC by VasylenchukMischa

# [Issue title](https://issueurl)
Add gifts
## Changes description
Add gift model and CRUD for it
## Screnshots of the added pages
![image](https://user-images.githubusercontent.com/38836502/120714364-c7894780-c4cb-11eb-99ae-619223dcf71a.png)
![image](https://user-images.githubusercontent.com/38836502/120714418-d5d76380-c4cb-11eb-954b-50460bc54824.png)
![image](https://user-images.githubusercontent.com/38836502/120714457-e4be1600-c4cb-11eb-8ed4-e91c2bb7515c.png)

## Check list:
- [ ] Integration Tests
- [x] Functional
- [x] Unit
- [x] Factories
- [ ] Updated seed file

2021-06-04 06:40 UTC, manastyretskyi requested changes

2021-06-04 06:40 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +    @gift = current_gifts.new(gift_params)
а тут перевіряти чи в юзера є права створювати гіфти не треба?

2021-06-04 06:40 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +  def current_gifts
не треба `current_gifts`, просто `collection`

2021-06-04 06:40 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +      redirect_to new_account_gift_path
чому тут редірект з флешем? такий ріспонс юзеру не очевидний, я б подумав що це на сервері п'ятсота помилка сталася, а не що я невірні данні ввів

2021-06-04 06:40 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +    @gift = current_gifts.find(params[:id])
зроби це так, як це в інших контролерах реалізовано

2021-06-04 06:40 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +      render :new
чому при апдейді рендериться `new`?

2021-06-04 06:40 UTC, manastyretskyi commented on app/javascript/stylesheets/gifts/form.scss
> +}
пишу уже п'ятий раз, робіть відступи між класами, і додавайте пусту строку в кінці кожного файлі

2021-06-04 06:40 UTC, manastyretskyi commented on app/models/gift.rb
> +  GIFTS_TYPE = [MERCH, COUPON].freeze
це масив, має бути множина

2021-06-04 06:40 UTC, manastyretskyi commented on app/policies/account/gift_policy.rb
> +    user.role.admin?
може зробити делігейти чи щось таке для юзера на роль? писати всюди `user.role.admin?` напряжно

2021-06-04 06:40 UTC, manastyretskyi commented on app/views/account/gifts/edit.html.slim
> +  = render 'account/gifts/form', gift: @gift, path: [:account, @gift], back_path: [:account, @gift]
щось цей `path` i `back_path` мені тут лишніми виглядають

2021-06-04 06:40 UTC, manastyretskyi commented on app/views/account/gifts/index.html.slim
> +h2 = @current_organization.name
зроби хелпер метод `current_organization`, і не використовуй тут інстанс змінну

2021-06-04 06:40 UTC, manastyretskyi commented on app/views/account/gifts/_form.html.slim
> += simple_form_for @gift, url: path do |f|
для чого ти передаєш в паршиал gift, якщо тут всеодно юзаєш інстанс змінну?

2021-06-04 06:40 UTC, manastyretskyi commented on app/views/static_pages/_header.html.slim
> +      = button_to 'Sign Up', new_user_registration_path, method: :get, class: "btn btn-primary btn-lg btn-bg-color"
для чого тут робити `button_to`, якщо це просто метод `GET`?

2021-06-04 06:40 UTC, manastyretskyi commented on db/migrate/20210602082028_create_gifts.rb
> +      t.references :organization
а тут не треба чогось типу `price`?

2021-06-04 06:43 UTC, VasylenchukMischa commented on db/migrate/20210602082028_create_gifts.rb
> +      t.references :organization
amoun це price

2021-06-04 06:55 UTC, manastyretskyi commented on db/migrate/20210602082028_create_gifts.rb
> +      t.references :organization
![image](https://user-images.githubusercontent.com/43040379/120758701-d1866700-c51a-11eb-9180-60ef818c4bfb.png)
мені здається що тут не ціна мається на увазі, але не впевнений, може то у мене англійська не гуд просто ;-)

2021-06-04 10:44 UTC, vmyts539 commented on db/migrate/20210602082028_create_gifts.rb
> +      t.references :organization
> amount це price

![image](https://user-images.githubusercontent.com/33605808/120790006-0bfffc00-c53b-11eb-9df1-7c030ffeab8f.png)

2021-06-04 10:46 UTC, VasylenchukMischa commented on db/migrate/20210602082028_create_gifts.rb
> +      t.references :organization
Я вже виправив, нам потрібна кількість і ціна, тому я додав ще одне поле

2021-06-06 19:59 UTC, igorkasyanchuk commented on app/assets/stylesheets/account/my_organization.scss
> +// Place all the styles related to the Account/MyOrganization controller here.
Цей файл потрібний?

2021-06-06 19:59 UTC, igorkasyanchuk commented on app/controllers/account/gifts_controller.rb
> +    @gift = collection.find(params[:id])
Зроби метод resource який шукає з collection рекорд і юзай його

2021-06-06 20:00 UTC, VasylenchukMischa commented on app/assets/stylesheets/account/my_organization.scss
> +// Place all the styles related to the Account/MyOrganization controller here.
Багато змін, забув видалити

2021-06-06 20:00 UTC, igorkasyanchuk commented on app/helpers/account/gifts_helper.rb
> +  def current_organization
Зроби helper method in application controller так і гугли приклад

А це перенеси туди

2021-06-06 20:01 UTC, manastyretskyi requested changes

2021-06-06 20:01 UTC, manastyretskyi commented on app/assets/stylesheets/account/my_organization.scss
> +// Place all the styles related to the Account/MyOrganization controller here.
пустий файл видали

2021-06-06 20:01 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +    @gift = collection.find(params[:id])
зроби метод `resource`, як в інших контролерах

2021-06-06 20:01 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +      redirect_to new_account_gift_path
це не гуд, юзер експіріенс поганий, уяви собі що я заповнював форму подарунка хвилин 10 (припустим що це якась велика форма), нажав кнопку, а вона мене редіректить і каже що щось не ок, і я тепер маю заново її заповнювати

2021-06-06 20:01 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +      redirect_to edit_account_gift_path
то саме що й вище

2021-06-06 20:01 UTC, manastyretskyi commented on app/controllers/account/my_organizations_controller.rb
> +class Account::MyOrganizationsController < Account::AccountsController
а що, може бути `not_my_organizations`? чому не просто `organizations`?

2021-06-06 20:01 UTC, manastyretskyi commented on app/helpers/account/gifts_helper.rb
> +  def current_organization
це не добре, видали це. і почитай про хелпер методи

2021-06-06 20:01 UTC, manastyretskyi commented on app/javascript/stylesheets/application.scss
> +@import "gifts/form.scss";
формат не треба вказувати

2021-06-06 20:01 UTC, manastyretskyi commented on app/javascript/stylesheets/gifts/form.scss
> +  font-family: Arial, Helvetica, sans-serif;
звідки ці шрифти взялися?

2021-06-06 20:01 UTC, manastyretskyi commented on app/models/role.rb
> +
?

2021-06-06 20:01 UTC, manastyretskyi commented on app/models/user.rb
> +  has_many :colleagues, -> { where.not(users: { id: id }) }, through: :organization, source: :users, class_name: 'User'
це не добре, то айді яке ти там викликаєш це не те айді про яке ти думаєш

2021-06-06 20:01 UTC, manastyretskyi commented on app/models/user.rb
> +  has_many :colleagues, -> { where.not(users: { id: id }) }, through: :organization, source: :users, class_name: 'User'
покажи мені кверю яку воно генерує

2021-06-06 20:01 UTC, manastyretskyi commented on app/policies/account/gift_policy.rb
> +  delegate :admin?, to: :user
думаю цього не треба, краще явно писати `user.admin?`

2021-06-06 20:01 UTC, manastyretskyi commented on app/views/account/gifts/edit.html.slim
> +  = link_to 'Back', account_gifts_path, class: "gift-text-size btn btn-primary"
це так задумано що воно всьо в тезі `h1`?

2021-06-06 20:01 UTC, manastyretskyi commented on app/views/account/gifts/index.html.slim
> +    = render 'gift', gift: gift
що це за список без `li`?

2021-06-06 20:01 UTC, manastyretskyi commented on app/views/account/gifts/new.html.slim
> +  = link_to 'Back', account_gifts_path
те саме, всьо в хедері

2021-06-06 20:01 UTC, igorkasyanchuk commented on app/javascript/stylesheets/gifts/form.scss
> +  display: flex;
Бутстрап мав би мати теж стилі щоб задати флекс

2021-06-06 20:01 UTC, igorkasyanchuk commented on app/models/gift.rb
> +
Навіщо set?

2021-06-06 20:03 UTC, VasylenchukMischa commented on app/models/gift.rb
> +
Любомир казав вище

2021-06-06 20:05 UTC, manastyretskyi commented on app/models/gift.rb
> +
Я не те мав на увазі, у тебе воно було в однині написано, `GIFT_TYPE`, мало бути `GIFT_TYPES`

2021-06-06 20:10 UTC, vmyts539 commented on app/assets/stylesheets/account/my_organization.scss
> +// Place all the styles related to the Account/MyOrganization controller here.
видаляйте автогенеровані файли якщо в них нічого не пишите

2021-06-06 20:10 UTC, vmyts539 commented on app/controllers/account/gifts_controller.rb
> +      redirect_to new_account_gift_path
render*

2021-06-06 20:10 UTC, vmyts539 commented on app/controllers/account/gifts_controller.rb
> +      redirect_to edit_account_gift_path
те саме

2021-06-06 20:10 UTC, vmyts539 commented on app/models/gift.rb
> +  belongs_to :organization
константи вище асоціацій
![image](https://user-images.githubusercontent.com/33605808/120938544-e8e07280-c71b-11eb-8279-74df2b74572e.png)

2021-06-06 20:10 UTC, vmyts539 commented on app/views/account/gifts/_form.html.slim
> +  = f.input :description, label: "Please, add some description", as: :text, :html_input => {:cols => 5, :rows => 15}, label_html: {class:  "gift-text-size"}
код стайл, юзай один тип хеша, або class: "gift-text-size", або :rows => 15

2021-06-06 20:15 UTC, VasylenchukMischa commented on app/models/gift.rb
> +
😅

2021-06-06 20:50 UTC, igorkasyanchuk commented on app/views/account/gifts/index.html.slim
> +    = render 'gift', gift: gift
Додай повний шлях до паршала

2021-06-06 20:50 UTC, igorkasyanchuk commented on app/views/account/my_organizations/edit.html.slim
> +  = f.file_field :logo, label: "Change logo", multiple: true, label_html: {class:  "gift-text-size"}
А чого тут мультіпл

2021-06-06 20:50 UTC, igorkasyanchuk commented on config/routes.rb
>    end
Тут має бути resource :my_organization

2021-06-08 15:35 UTC, igorkasyanchuk commented on app/assets/stylesheets/account/my_organization.scss
> +// They will automatically be included in application.css.
так файл вже видалений чи ні?

2021-06-08 15:37 UTC, igorkasyanchuk commented on app/javascript/stylesheets/forms.scss
> +.gift-create-form {
а буде інша форма там як буде ще раз такий самий код?
видаляй

може просто форма має бути в контейнері якомусь,
взагалі сторінка має мати контейнер

2021-06-08 15:38 UTC, igorkasyanchuk commented on app/policies/account/gift_policy.rb
> +    user.admin?
а чому тут не використовується те що робить делегейт?

2021-06-08 15:38 UTC, VasylenchukMischa commented on app/assets/stylesheets/account/my_organization.scss
> +// They will automatically be included in application.css.
Видалений

2021-06-08 15:38 UTC, VasylenchukMischa commented on app/assets/stylesheets/account/my_organization.scss
> +// They will automatically be included in application.css.
локально

2021-06-08 15:38 UTC, igorkasyanchuk commented on app/policies/account/user_policy.rb
> +    admin? || manager?
от я тут використовується делегейт
+ де воно в базовому класі щоб не писати всюди одне і те саме (я про делегейт що зверху)

2021-06-08 15:39 UTC, igorkasyanchuk commented on app/views/account/gifts/_gift.html.slim
> +td.text-center = gift.description
забери це центрування, реально не гарно буде коли все по центру

2021-06-08 15:39 UTC, igorkasyanchuk commented on app/views/account/gifts/_gift.html.slim
> +td.text-center = gift.description
я про .text-center

2021-06-08 15:40 UTC, VasylenchukMischa commented on app/views/account/gifts/_gift.html.slim
> +td.text-center = gift.description
![image](https://user-images.githubusercontent.com/38836502/121215722-ecddd300-c888-11eb-8482-8183833ca8d4.png)

2021-06-08 15:40 UTC, VasylenchukMischa commented on app/views/account/gifts/_gift.html.slim
> +td.text-center = gift.description
Воно так виглядає, забирати?

2021-06-08 15:40 UTC, igorkasyanchuk commented on app/views/account/gifts/show.html.slim
> +.content-page.mt-4
мені винлядає що в лайауті самому може бути 



'''
   .content-page.mt-4
   .content
    .container-fluid
'''

бо може воно буде на всіх сторінках таке?

2021-06-08 15:41 UTC, VasylenchukMischa commented on app/views/account/gifts/show.html.slim
> +.content-page.mt-4
може

2021-06-08 15:51 UTC, VasylenchukMischa commented on app/policies/account/user_policy.rb
> +    admin? || manager?
Делегейт прибрав, тому що навіщо його, так наглядніше, що ми дізнаємося роль конкретно юзера

2021-06-08 17:08 UTC, manastyretskyi commented on app/policies/account/user_policy.rb
> +    admin? || manager?
Це я сказав щоб в полісі не використовувати делегейти

2021-06-08 17:19 UTC, manastyretskyi requested changes, later dismissed

2021-06-08 17:19 UTC, manastyretskyi commented on Gemfile
> +  gem 'rails-controller-testing'
не треба контролер тестів, пиши ріквест тести

2021-06-08 17:19 UTC, manastyretskyi commented on Gemfile
> +  gem 'rails-controller-testing'
Писав це уже в двох ПРах

2021-06-08 17:19 UTC, manastyretskyi commented on app/controllers/account/gifts_controller.rb
> +    if @gift.save
```suggestion
    if @gift.update(gift_params)
```

2021-06-08 17:19 UTC, manastyretskyi commented on app/javascript/stylesheets/forms.scss
> +}
додавай пусту строку в кінці файлу

2021-06-08 17:19 UTC, manastyretskyi commented on app/models/gift.rb
> +  validates :gift_type, inclusion: { in: gift_types.values }
зроби ордер так як [стайлгайді](https://github.com/rubocop/rails-style-guide#macro-style-methods)

2021-06-08 17:19 UTC, manastyretskyi commented on app/models/role.rb
> +
забери цей таб

2021-06-08 17:19 UTC, manastyretskyi commented on app/models/user.rb
> +  delegate :superadmin?, :admin?, :manager?, to: :role
додай ще `simple?`

2021-06-08 17:19 UTC, manastyretskyi commented on app/models/user.rb
> +  end
верни асоціацію, лямбда в асоціації приймає параметри, там є айді об'єкта

2021-06-09 06:29 UTC, manastyretskyi commented on app/models/role.rb
> +  enum role: { superadmin: SUPERADMIN, admin: ADMIN, manager: MANAGER, simple: USER }
ти всюди змінив `user` на `simple` (я про значення поля, його можна символом задавати просто)

2021-06-09 06:30 UTC, manastyretskyi commented on app/views/account/gifts/_gift.html.slim
> +  td = gift.name
чому так?

2021-06-09 06:31 UTC, manastyretskyi commented on spec/factories/gifts.rb
> +    organization
а тут `price` не треба додати?

2021-06-09 06:31 UTC, manastyretskyi commented on app/assets/stylesheets/account/my_organization.scss
> +// They will automatically be included in application.css.
Видали цей файл

2021-06-09 06:32 UTC, VasylenchukMischa commented on app/assets/stylesheets/account/my_organization.scss
> +// They will automatically be included in application.css.
Видалив!

2021-06-09 06:34 UTC, VasylenchukMischa commented on app/assets/stylesheets/account/my_organization.scss
> +// They will automatically be included in application.css.
![image](https://user-images.githubusercontent.com/38836502/121305089-d6299180-c905-11eb-9819-d1b60edf2628.png)

2021-06-09 06:38 UTC, VasylenchukMischa commented on app/views/account/gifts/_gift.html.slim
> +  td = gift.name
Того не треба, випадково запушив

2021-06-09 07:01 UTC, manastyretskyi commented on app/views/account/gifts/index.html.slim
> +            tr = render 'account/gifts/gift', gift: gift
так не треба розбивати на паршиали, по ідеї паршиал має бути такий щоб його можна було будь де відрендерити, і він всюди одинаково виглядав, а твій буде виглядати так як треба тільки за умови якщо він конкретно в ці табличці, і коли мені треба буде додати нову колонку до неї, мені треба буде в кількох місцях міняти, це не зручно

2021-06-09 07:29 UTC, igorkasyanchuk approved these changes

2021-06-09 08:07 UTC, DenysVinegod approved these changes

2021-06-09 08:08 UTC, everlastroman approved these changes

2021-06-09 08:08 UTC, merged